"use client";

import { useState } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";

type Step2ContentProps = {
  rearrangedContent: string;
  suggestions: string[];
  onSubmit: (data: { selectedHeadline: string; finalContent: string }) => void;
  onBack: () => void;
};

export default function Step2Content({
  rearrangedContent,
  suggestions,
  onSubmit,
  onBack,
}: Step2ContentProps) {
  const [finalContent, setFinalContent] = useState(rearrangedContent);
  const [selectedHeadline, setSelectedHeadline] = useState(
    suggestions.length > 0 ? suggestions[0] : ""
  );

  const handleSubmit = () => {
    onSubmit({ selectedHeadline, finalContent });
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Refine Your Content</CardTitle>
        <CardDescription>
          Choose a headline and edit the main content generated by our AI.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-8">
        <div className="space-y-4">
          <Label className="font-semibold text-lg">Choose Your Headline</Label>
          <RadioGroup
            value={selectedHeadline}
            onValueChange={setSelectedHeadline}
            className="space-y-2"
          >
            {suggestions.map((suggestion, index) => (
              <div key={index} className="flex items-center space-x-2">
                <RadioGroupItem value={suggestion} id={`suggestion-${index}`} />
                <Label htmlFor={`suggestion-${index}`} className="font-normal">
                  {suggestion}
                </Label>
              </div>
            ))}
          </RadioGroup>
        </div>
        <div className="space-y-4">
          <Label htmlFor="main-content" className="font-semibold text-lg">
            Edit Main Content
          </Label>
          <Textarea
            id="main-content"
            value={finalContent}
            onChange={(e) => setFinalContent(e.target.value)}
            rows={10}
            className="resize-y"
          />
        </div>
      </CardContent>
      <CardFooter className="flex justify-between">
        <Button variant="outline" onClick={onBack}>
          Back
        </Button>
        <Button onClick={handleSubmit}>Select Theme</Button>
      </CardFooter>
    </Card>
  );
}
