import React from 'react';
import { PolicyPageLayout } from '@/components/PolicyPageLayout';

export default function PrivacyPolicy() {
  return (
    <PolicyPageLayout
      title="Privacy Policy"
      content={
        <div className="space-y-6 text-gray-700 leading-relaxed text-sm">
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3 border-l-4 border-brand-navy pl-3">Introduction</h2>
            <p>Welcome to <strong>Shopwave</strong>.</p>
            <p>
              Our Privacy Policy governs your visit to <a href="https://www.shopwave.social/dropshipping" className="text-blue-600 hover:underline">https://www.shopwave.social/dropshipping</a>, and explains how we collect, safeguard and disclose information that results from your use of our Service.
            </p>
            <p>
              We use your data to provide and improve Service. By using the Service, you agree to the collection and use of information in accordance with this policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3 border-l-4 border-brand-navy pl-3">Definitions</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>SERVICE</strong> means the https://www.shopwave.social/dropshipping website operated by Shopwave.</li>
              <li><strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data.</li>
              <li><strong>USAGE DATA</strong> is data collected automatically either generated by the use of Service or from Service infrastructure.</li>
              <li><strong>COOKIES</strong> are small files stored on your device.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3 border-l-4 border-brand-navy pl-3">Information Collection and Use</h2>
            <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
            <p><strong>Types of Data Collected:</strong></p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Cookies and Usage Data</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3 border-l-4 border-brand-navy pl-3">Use of Data</h2>
            <p>Shopwave uses the collected data for various purposes:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>To provide and maintain our Service.</li>
              <li>To notify you about changes to our Service.</li>
              <li>To provide customer support.</li>
              <li>To gather analysis or valuable information so that we can improve our Service.</li>
              <li>To monitor the usage of our Service.</li>
              <li>To detected, prevent and address technical issues.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3 border-l-4 border-brand-navy pl-3">Security of Data</h2>
            <p>
              The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3 border-l-4 border-brand-navy pl-3">Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, please contact us by email: <strong>shopwave.social@gmail.com</strong>.</p>
          </section>
        </div>
      }
    />
  );
}
